version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@2.0.0
jobs:
  build:
    working_directory: ~/dapps-election
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: cimg/node:17.0.1
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: trufflesuite/ganache-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check npm version
          command: 'npm version'
      - run:
          name: Check node version
          command: 'node --version'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm 
          command: npm install
      - run:
          name: Migrate Contracts
          command: ./node_modules/truffle/build/cli.bundled.js migrate --network circleci
      - run:
          name: Test Contracts
          command: ./node_modules/truffle/build/cli.bundled.js test --network circleci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build and push docker
          command: |
            export TAG=0.1.${CIRCLE_BUILD_NUM}
            docker build -t cyyeong/dapps-election:$TAG .
            echo xxx | docker login -u cyyeong --password-stdin
            docker push cyyeong/dapps-election:$TAG
